#!/usr/bin/env perl

#Includes
use strict;
use warnings;
use Getopt::Long;
use Data::Dumper;
use File::Basename;
use Cwd;
my $scriptDir;
my $libDir;
my $envName;
my $rFunctions;
BEGIN
{
	$scriptDir = Cwd::abs_path(dirname($0));
	my $lib = dirname($scriptDir);
	if($lib =~ m/mv_utilities/)
	{
		my $mvDir = $lib;
		$lib =~ s/mv_utilities.*/perl_utilities/;
		$mvDir =~ s/mv_utilities.*/mv_utilities/;
		$libDir = Cwd::abs_path($lib) . "/lib";
		$rFunctions = $mvDir . "/scripts/scripts/hms_R_functions/hms_R_functions.R";
	}
	else
	{
		$lib = `conda info -e | grep '*'`;
		$lib =~ s/^.*\*//;
		$lib =~ s/^\s+|\s+$//g;
		my $sitePath = `python -m site | grep $lib | grep -P "site-packages'"`;
		$sitePath =~ s/^\s+|\s+$//g;
		$sitePath =~ s/('|,)//g;
		$libDir = $sitePath . "/lib";
		$rFunctions = $sitePath . "/scripts/scripts/hms_R_functions/hms_R_functions.R";
	}
	$envName = `conda info -e | grep '*'`;
	$envName =~ s/\*.*//;
	$envName =~ s/^\s+|\s+$//g;
}
use lib $libDir;
use MiscFunctions;

my @ogArgs = @ARGV;
if(-e "debug")
{
	print "ARGV for " . $0 . ":\n";
	print Dumper(@ogArgs);
}

my $timeBegin = time();

my $debug;
my ($inFile,$outFile,$cols);

GetOptions(
	"debug"     =>\$debug,
	"inFile=s"	=>\$inFile,
	"outFile=s"	=>\$outFile,
	"cols=s"		=>\$cols
);

die "-inFile parameter is required\n" unless $inFile;
die "-outFile parameter is required\n" unless $outFile;
die "-cols parameter is required\n" unless $cols;

my $rScript = generateRScript();
my $systemCall = join(" ","Rscript","--vanilla",$rScript,$inFile,$outFile,"\"" . $cols . "\"");
system($systemCall);
system("rm " . $rScript);

system("chmod 777 -R --silent .");

my $timeEnd = time();

my $runTime = $timeEnd - $timeBegin;
#print "\nProcess Complete: " . $0 . "\n";
my $minutes = $runTime/60;
#print "Job took " . $minutes ." minutes\n";

#End of main code

sub generateRScript
{
	my %args = @_;
	my $returnFile = "replace_hyphens.R";
	open my $ofh, ">", $returnFile;
	print $ofh "source(\"" . $rFunctions . "\")\n";
	print $ofh "args = commandArgs(trailingOnly=TRUE)\n";
	print $ofh "\n";
	print $ofh "infile<-args[1]\n";
	print $ofh "outfile<-args[2]\n";
	print $ofh "cols<-args[3]\n";
	print $ofh "\n";
	print $ofh "data<-read.csv(infile,header=T,stringsAsFactors=F,sep=\"\\t\",colClasses=\"character\")\n";
	print $ofh "\n";
	print $ofh "for (i in unlist(strsplit(cols,split=\" \"))){\n";
	print $ofh " print(i)\n";
	print $ofh " data[[i]]<-gsub(\"-\",\"\",data[[i]])\n";
	print $ofh "}\n";
	print $ofh "\n";
	print $ofh "write.hms(data,outfile)\n";
	close $ofh;
	return $returnFile;
}



































