#!/usr/bin/env perl

#Includes
use strict;
use warnings;
use Getopt::Long;
use Data::Dumper;
use File::Basename;
use Cwd;
my $scriptDir;
my $libDir;
my $envName;
my $rScript;
BEGIN
{
	$scriptDir = Cwd::abs_path(dirname($0));
	my $lib = dirname($scriptDir);
	if($lib =~ m/mv_utilities/)
	{
		my $mvDir = $lib;
		$lib =~ s/mv_utilities.*/perl_utilities/;
		$mvDir =~ s/mv_utilities.*/mv_utilities/;
		$libDir = Cwd::abs_path($lib) . "/lib";
		$rScript = $mvDir . "/scripts/clientScripts/Tea_Leaves/Tea_Leaves_SS/Tea_Leaves_SS_filter.R";
	}
	else
	{
		$lib = `conda info -e | grep '*'`;
		$lib =~ s/^.*\*//;
		$lib =~ s/^\s+|\s+$//g;
		my $sitePath = `python -m site | grep $lib | grep -P "site-packages'"`;
		$sitePath =~ s/^\s+|\s+$//g;
		$sitePath =~ s/('|,)//g;
		$libDir = $sitePath . "/lib";
		$rScript = $sitePath . "/scripts/clientScripts/Tea_Leaves/Tea_Leaves_SS/Tea_Leaves_SS_filter.R";
	}
	$envName = `conda info -e | grep '*'`;
	$envName =~ s/\*.*//;
	$envName =~ s/^\s+|\s+$//g;
}
use lib $libDir;
use MiscFunctions;

my @ogArgs = @ARGV;
if(-e "debug")
{
	print "ARGV for " . $0 . ":\n";
	print Dumper(@ogArgs);
}

my $timeBegin = time();

my ($inDir,$outDir,$npiList,$filterCol,$allCodes);
my $debug;

GetOptions(
	"inDir=s"		=>\$inDir,
	"outDir=s"		=>\$outDir,
	"npiList=s"		=>\$npiList,
	"filterCol=s"	=>\$filterCol,
	"allCodes=s"	=>\$allCodes,
	"debug"			=>\$debug
);

die "-inDir parameter is required (linux path)\n" unless $inDir;
die "-outDir parameter is required (linux path)\n" unless $outDir;
die "-npiList parameter is required (single field NPI list with NPI header)\n" unless $npiList;
die "-filterCol parameter is required (field position)\n" unless $filterCol;
die "-allCodes parameter is required (0|1)\n" unless defined $allCodes;

system("Rscript " . $rScript . " " . join(" ",$inDir,$outDir,$npiList,$filterCol,$allCodes));

system("chmod 777 -R --silent " . $outDir);

my $timeEnd = time();

my $runTime = $timeEnd - $timeBegin;
#print "\nProcess Complete: " . $0 . "\n";
my $minutes = $runTime/60;
#print "Job took " . $minutes ." minutes\n";

#End of main code




































