#!/usr/bin/env perl

=head1 NAME

manip

=head1 COMMAND

perl /vol/cs/clientprojects/Facility_Automation/scripts/manip.pl -config <settings.cfg>

=head1 DESCRIPTION

code template (insert description here)

=head1 AUTHOR

Stephen Siu mm/dd/yyyy

=cut

#Includes
use strict;
use warnings;
use Getopt::Long;
use Data::Dumper;
use File::Basename;
use Cwd;
my $scriptDir;
my $libDir;
my $rScript;
BEGIN
{
	$scriptDir = Cwd::abs_path(dirname($0));
	my $lib = dirname($scriptDir);
	if($lib =~ m/mv_utilities/)
	{
		$lib =~ s/mv_utilities.*/mv_utilities/;
		$rScript = Cwd::abs_path($lib) . "/scripts/scripts/classify_codes/classify_codes.R";
	}
	else
	{
		$lib = `conda info -e | grep '*'`;
		$lib =~ s/^.*\*//;
		$lib =~ s/^\s+|\s+$//g;
		my $sitePath = `python -m site | grep $lib | grep -P "site-packages'"`;
		$sitePath =~ s/^\s+|\s+$//g;
		$sitePath =~ s/('|,)//g;
		$rScript = $sitePath . "/scripts/scripts/classify_codes/classify_codes.R";
	}
}

my @ogArgs = @ARGV;
$| = 1;

my $codeList;
my $codeType;
my $debug;

GetOptions(
   "codeList=s"	=>\$codeList,
	"debug"			=>\$debug
);

die "-codeList parameter is required\n" unless $codeList;

system("Rscript --vanilla " . $rScript . " " . $codeList);
system("chmod 777 -R --silent .");

#End of main code







































