#!/usr/bin/env perl

#Includes
use strict;
use warnings;
use Getopt::Long;
use Data::Dumper;
use File::Basename;
use Cwd;
my $scriptDir;
my $libDir;
my $envName;
my $rScript;
BEGIN
{
	$scriptDir = Cwd::abs_path(dirname($0));
	my $lib = dirname($scriptDir);
	if($lib =~ m/mv_utilities/)
	{
		my $mvDir = $lib;
		$lib =~ s/mv_utilities.*/perl_utilities/;
		$mvDir =~ s/mv_utilities.*/mv_utilities/;
		$libDir = Cwd::abs_path($lib) . "/lib";
		$rScript = $mvDir . "/scripts/clientScripts/Tea_Leaves/tea_leaves_project_QA/tea_leaves_project_QA_v1.R";
	}
	else
	{
		$lib = `conda info -e | grep '*'`;
		$lib =~ s/^.*\*//;
		$lib =~ s/^\s+|\s+$//g;
		my $sitePath = `python -m site | grep $lib | grep -P "site-packages'"`;
		$sitePath =~ s/^\s+|\s+$//g;
		$sitePath =~ s/('|,)//g;
		$libDir = $sitePath . "/lib";
		$rScript = $sitePath . "/scripts/clientScripts/Tea_Leaves/tea_leaves_project_QA/tea_leaves_project_QA_v1.R";
	}
	$envName = `conda info -e | grep '*'`;
	$envName =~ s/\*.*//;
	$envName =~ s/^\s+|\s+$//g;
}
use lib $libDir;
use MiscFunctions;

my @ogArgs = @ARGV;
if(-e "debug")
{
	print "ARGV for " . $0 . ":\n";
	print Dumper(@ogArgs);
}

my $timeBegin = time();

my $debug;
my $oldDir;
my $newDir;
my $outFile;
my $prefix;

GetOptions(
	"debug"		=>\$debug,
	"oldDir=s"	=>\$oldDir,
	"newDir=s"	=>\$newDir,
	"outFile=s"	=>\$outFile,
	"prefix=s"	=>\$prefix
);

die "-oldDir parameter is required\n" unless $oldDir;
die "-newDir parameter is required\n" unless $newDir;
die "-outFile parameter is required\n" unless $outFile;
die "-prefix parameter is required\n" unless $prefix;

foreach my $x ($oldDir,$newDir)
{
	$x =~ s/\/+$//;
	$x = Cwd::abs_path($x);
}

system("Rscript " . $rScript . " " . join(" ",$newDir,$oldDir,$outFile,$prefix));

system("chmod 777 -R --silent " . $outFile);

my $timeEnd = time();

my $runTime = $timeEnd - $timeBegin;
#print "\nProcess Complete: " . $0 . "\n";
my $minutes = $runTime/60;
#print "Job took " . $minutes ." minutes\n";

#End of main code




































